### ISSUE TITLE
"PHP Fatal error: Class 'Buzz\\Browser' not found" when using guzzlehttp/guzzle library

### ISSUE THREAD

**Issue by jaimeeee** [toin0u/DigitalOceanV2#104]
I tried installing DigitalOceanV2 though composer with the **guzzlehttp/guzzle** library, but once using it I got this error:

    PHP Fatal error: Class 'Buzz\\Browser' not found in /SITE/vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php on line 43

Then I changed my library to **kriswallsmith/buzz** and it worked, so I suppose it might be a bug?

**Comment by sevenpixels** [comment]
@jaimeeee it's not a bug, the documentation is a little off in the example. It loads the Buzz adapter rather than the Guzzle adapter. Just use the code below and it works.

```php
use DigitalOceanV2\Adapter\Guzzle5Adapter;
use DigitalOceanV2\DigitalOceanV2;

$adapter = new Guzzle5Adapter($token);
$digitalocean = new DigitalOceanV2($adapter);
```

**Comment by GrahamCampbell** [comment]
If you want to use buzz, install it; if you want guzzle, install that. Sorry if that wasn't clear.

**Comment by jaimeeee** [comment]
It was clear, I ended up using another library, that's why I posted this issue. So it's only an issue on the documentation then? Why not update it? :)

Thanks!

**Comment by bitwombat** [comment]
This needs to be re-opened. There is no DigitalOceanV2\Adapter\Guzzle5Adapter in the current codebase, yet the original problem remains of Guzzle being mandatory (despite the examples in README.md).

**Comment by GrahamCampbell** [comment]
It's called `GuzzleHttpAdapter`.

**Comment by GrahamCampbell** [comment]
And the documentation on the readme is not "a little off". It says it is showing the Buzz adapter as an example.

**Comment by dragmecom** [comment]
Would just recommend adding a Guzzle and Buzz versions of the example, since it's making people get lost.
