### ISSUE TITLE
OpenSky Symfony2-coding-standard repo is 404

### ISSUE THREAD

**Issue by jeremykendall** [toin0u/DigitalOceanV2#107]
From CONTRIBUTING.md

> This library will use the Symfony2 Coding Standard. The easiest way to apply these conventions is to install PHP_CodeSniffer and the [Opensky Symfony2 Coding Standard](http://symfony.com/doc/current/contributing/code/standards.html).

The [OpenSky Symfony2 coding standard repository] is 404. Is there another set of PHP_CodeSniffer rules that might replace the OpenSky rules?

**Comment by GrahamCampbell** [comment]
Can we change this to say use php-cs-fixer - by definition, that is correct, and anything else needs to match php-cs-fixer's behaviour, otherwise it's wrong.

**Comment by jeremykendall** [comment]
:100:

**Comment by toin0u** [comment]
@jeremykendall Thanks for reporting it. Do you mind to make a PR? :)

**Comment by jeremykendall** [comment]
@toin0u Done!
