### ISSUE TITLE
422 at droplet creation.

### ISSUE THREAD

**Issue by cagataygurturk** [toin0u/DigitalOceanV2#112]
Since yesterday I am getting 422 when I am trying to create a droplet. Fixing the header as follows helped to resolve:

https://github.com/cagataygurturk/DigitalOceanV2/commit/0324eb8bb8e59b3def2554cfdbb21b4c0c981834

All the post requests might be problematic. Can you look if you have the same problem?

**Comment by splitice** [comment]
Can second this, additionally this statement is extremely duplicated - should be abstracted into adapter.

**Comment by GrahamCampbell** [comment]
What adapter?

**Comment by GrahamCampbell** [comment]
Fixed. Turns out some bad assumptions where made that didn't work across all adapters.

**Comment by GrahamCampbell** [comment]
Let me know if my fix worked for you.

**Comment by GrahamCampbell** [comment]
> Can second this, additionally this statement is extremely duplicated - should be abstracted into adapter.

Yeh, I totally agree, and I've made that change.

**Comment by GrahamCampbell** [comment]
I've just manually tested droplet creation and deletion using buzz 0.15, guzzle 3.9, guzzle 5.3, and guzzle 6.1. All of them work now.
