### ISSUE TITLE
Clone Droplet

### ISSUE THREAD

**Issue by pedroparraortega** [toin0u/DigitalOceanV2#120]
Hi congrats 4 your work, it's awesome bundle. I'm using it on my symfony2 app and i would to know how could i clone a droplet from snapshot???

Thx in advance

**Comment by GrahamCampbell** [comment]
https://github.com/toin0u/DigitalOceanV2/blob/master/src/Api/Droplet.php#L118

**Comment by GrahamCampbell** [comment]
https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet

**Comment by pedroparraortega** [comment]
i've tried to create a droplet using the droplet id, and name, but not working. i'll read again the documentation. thx

**Comment by pedroparraortega** [comment]
Sorry, i've tried the wrong image id.... soz

**Comment by yassirh** [comment]
You turnoff your droplet then take a snapshot of it and finally use the snapshot  (should be in images ) to create a new droplet.

**Comment by GrahamCampbell** [comment]
@yassirh

> a droplet from snapshot???

**Comment by yassirh** [comment]
@GrahamCampbell Yes, Actually a snapshot or a backup for that matter are accessible [through the API as images](https://developers.digitalocean.com/documentation/v2/#list-a-user-s-images) and to identify the last snapshot you can use the fields created_at and type.
