### ISSUE TITLE
Implement floating ips

### ISSUE THREAD

**Issue by yassirh** [toin0u/DigitalOceanV2#122]
"Floating IP objects represent a publicly-accessible static IP addresses that can be mapped to one of your Droplets. They can be used to create highly available setups or other configurations requiring movable addresses."

Documentation https://developers.digitalocean.com/documentation/v2/#floating-ips

**Comment by toin0u** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I thought I already implemented them?

**Comment by GrahamCampbell** [comment]
https://github.com/toin0u/DigitalOceanV2/blob/master/src/Api/FloatingIp.php

**Comment by yassirh** [comment]
Oh that's great! My local version was pointing at my fork which is out of date. My bad :)
