### ISSUE TITLE
SPL Loader request

### ISSUE THREAD

**Issue by patrioticcow** [toin0u/DigitalOceanV2#123]
I'm using some older code... is there an autoloader.php, somewhere..

thanks

**Comment by GrahamCampbell** [comment]
No, sorry. I'd recommend just writing your own generic psr4 autoloader, or just use composer's or symfony's.

**Comment by GrahamCampbell** [comment]
Or, just use composer?

**Comment by GrahamCampbell** [comment]
You can use composer with any code base, even if this package is the only thing installed into your code base with it.

**Comment by patrioticcow** [comment]
I managed to use composer... I just wanted to keep the current code practice I'm using.

Thanks
