### ISSUE TITLE
Create droplet with SSH key

### ISSUE THREAD

**Issue by tsramarnath** [toin0u/DigitalOceanV2#126]
To use SSH keys in your create request, simply add the new paramater ssh_key_ids with a comma separated list of SSH Key IDs that you would like added to the new server that you will create:

https://api.digitalocean.com/droplets/new?name=[DROPLET_NAME]&size_id=[SIZE_ID]&image_id=[IMAGE_ID]®ion_id=[REGION_ID]&client_id=[YOUR_CLIENT_ID]&ssh_key_ids=[SSH_KEY_ID1],[SSH_KEY_ID2]

ssh_key_ids=[SSH_KEY_ID1],[SSH_KEY_ID2]

**Comment by yassirh** [comment]
What is the issue? or the question?

**Comment by blakeitcc** [comment]
Not sure how to add SSH Keys using v2 PHP SDK.  e.g. $droplet->create('name', 'nyc1', '1gb', 2343432, [70217,70272,70553]);

How do you pass in an array of SSH key ids at the end causes an error?

**Comment by Teevio** [comment]
This functionality already exists in the Droplet creation code: https://github.com/toin0u/DigitalOceanV2/blob/master/src/Api/Droplet.php#L119
