### ISSUE TITLE
Echo Information

### ISSUE THREAD

**Issue by dinorhino** [toin0u/DigitalOceanV2#127]
Hello,

Just curious how I would exstract the information from the query and be able to echo it out on the page? For instance being able to echo the ID of the server in which has been created etc.

Hopefully you'll be able to help!

Cheers :smiley:

**Comment by yassirh** [comment]
@dinorhino sorry for the late response. Actually, when you create a Droplet you get a `DigitalOceanV2\Entity\Droplet` back that contains all the information about the newly created Droplet including its ID.
