### ISSUE TITLE
timeout problem

### ISSUE THREAD

**Issue by tahmasebi** [toin0u/DigitalOceanV2#128]
Sometimes I receive this error:
```
 Fatal error: Uncaught exception 'Buzz\Exception\RequestException' with message 'Operation timed out after 5875 milliseconds with 0 out of 0 bytes received' in D:\...\DigitalOceanV2\vendor\kriswallsmith\buzz\lib\Buzz\Client\Curl.php on line 29
```
Where is the problem? the problem is for my internet connection or DigitalOcean disconnects it?

**Comment by GrahamCampbell** [comment]
Looks like your internet connection is a bit wobbly.

**Comment by GrahamCampbell** [comment]
An easy fix is to use either of the guzzle adapters with their retry subscriber, by passing in a custom client instance as the 2nd param.
