### ISSUE TITLE
Getting "PHP Fatal error" when using BuzzAdapter

### ISSUE THREAD

**Issue by jimmydburr** [toin0u/DigitalOceanV2#146]
FYI, I'm getting an error in both my own code or just following the standard examples in the Readme.md when using the BuzzAdapter. Swapping out BuzzAdapter for GuzzleHttpAdapter cures the problem with no other code changes.

In every case, the problem lies in the BuzzAdapter's FileGetContents.php. Example:
PHP Fatal error:  Uncaught exception 'Buzz\Exception\RequestException' with message 'file_get_contents(https://api.digitalocean.com/v2/account): failed to open stream: operation failed' in /root/do-admin/digopher/vendor/kriswallsmith/buzz/lib/Buzz/Client/FileGetContents.php:28

Again, the workaround is to use another adapter. GuzzleHttpAdapter is working for me.

Thanks,

Jim...

**Comment by GrahamCampbell** [comment]
Thanks for the report.

**Comment by GrahamCampbell** [comment]
What version are you using please?

**Comment by jimmydburr** [comment]
From the composer file...
```
    "name"       : "toin0u/digitalocean-v2",
    "type"       : "library",
    "description": "DigitalOcean API v2 PHP 5.4+ library",
    "keywords"   : ["DigitalOcean", "API", "Cloud Hosting", "SSD", "VPS"],
    "homepage"   : "https://github.com/toin0u/DigitalOceanV2",
    "license"    : "MIT",
```
Please let me know if you need more info.

Thanks,

Jim...

**Comment by jimmydburr** [comment]
Thanks, Graham... here ya go.
```
guzzlehttp/guzzle      6.2.1  Guzzle is a PHP HTTP client library
guzzlehttp/promises    1.2.0  Guzzle promises library
guzzlehttp/psr7        1.3.1  PSR-7 message implementation
monolog/monolog        1.21.0 Sends your logs to files, sockets, inboxes, databases and various web services
psr/http-message       1.0.1  Common interface for HTTP messages
psr/log                1.0.1  Common interface for logging libraries
toin0u/digitalocean-v2 2.1.2  DigitalOcean API v2 PHP 5.4+ library
```

**Comment by GrahamCampbell** [comment]
I'm confused. You've reported an issue with the buzz adapter, yet you are using guzzle?

**Comment by jimmydburr** [comment]
Correct. I had no choice but to switch to guzzle to get my code to work. I am reporting the bug in Buzz, which if I recall correctly, is the default.

**Comment by GrahamCampbell** [comment]
> which if I recall correctly, is the default.

Nope, there is no default. Guzzle 6 is the one I'd recommend tho.

**Comment by screamolic** [comment]
im change using guzzle , but its show another error like this.
Class 'DigitalOceanV2\Adapter\Guzzle5Adapter' not found in C:\xampp\htdocs\digitalocean\index.php on line 48

and i got this "Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

**Comment by GrahamCampbell** [comment]
I think this should be fixed in the latest release. :)
