### ISSUE TITLE
SSH keys?

### ISSUE THREAD

**Issue by joegarbett** [toin0u/DigitalOceanV2#151]
In the function call, $dropley->create(...), there's the SSH keys argument, but its not clear what that is? 

Could you clarify for me if it Is the ID of the key from digitalocean, or the key itself??

**Comment by joegarbett** [comment]
Anyone?

**Comment by olivercarl** [comment]
It's the identifier of the SSH key, a number. You can find it with
	$oDigitalOcean = new DigitalOceanV2($adapter);
	$oKeyApi = $oDigitalOcean->key();
	$oKeys = $oKeyApi->getAll();
	var_dump( $oKeys );
