### ISSUE TITLE
FatalErrorException in GuzzleHttpAdapter.php line 135: #13

### ISSUE THREAD

**Issue by ghost** [toin0u/DigitalOceanV2#169]
Using: https://github.com/GrahamCampbell/Laravel-DigitalOcean

Got this installed and setup - updated my digitalocean.php config file with my tokens.

Running any command e.g.
DigitalOcean::connection('main')->region()->getAll();

Results in:
FatalErrorException in GuzzleHttpAdapter.php line 135:
Call to a member function getBody() on null

I am using guzzlehttp.

Token is correct if I run a DO API call manually via command line. I am running the site locally on XAMPP (no SSL)

**Comment by aggrogg** [comment]
Any update on this guys? Waiting for this for my project, cheers.

**Comment by GrahamCampbell** [comment]
We'd accept a PR to fix this from you. I won't be investigating this I'm afraid, due to time constraints.

**Comment by surgiie** [comment]
Was there a fix on this? Hitting the same issue.

**Comment by GrahamCampbell** [comment]
I think this should be fixed in the latest release. :)
