### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by screamolic** [toin0u/DigitalOceanV2#173]
anyone can give me example code to parser all data?

i got
Fatal error: Cannot use object of type DigitalOceanV2\Entity\Droplet as array in C:\xampp\htdocs\digitalocean\index.php on line 111

**Comment by PixellUp** [comment]
Parse what data? Be more specific. Also, it would help as if you show as around line 111

**Comment by Teevio** [comment]
@screamolic data passed back is in object format, sounds like you are trying to use it as an array.  It'd be helpful to see the code you are talking about, as that would help us point you in the correct direction.

**Comment by yassirh** [comment]
@screamolic can you show us some code? with a clearer description of your issue?

**Comment by screamolic** [comment]
sorry my bad. im still learning php. i need more example.  :)
