### ISSUE TITLE
DomainRecord Update

### ISSUE THREAD

**Issue by iRuisu** [toin0u/DigitalOceanV2#175]
Would anyone be able to give me an example on how to update a DomainRecord, preferably an NS record?

Thank you!

**Comment by Teevio** [comment]
Hi there @iRuisu , I'd highly recommend you look at the source code for updating the DomainRecord: 

https://github.com/toin0u/DigitalOceanV2/blob/master/src/Api/DomainRecord.php#L129

as well as the corresponding API docs:

https://developers.digitalocean.com/documentation/v2/#update-a-domain-record

As it pertains to this API, the `$domainName` and the `$recordId` are required.  If you do not have these available you can grab them with the `getAll` call: https://github.com/toin0u/DigitalOceanV2/blob/master/src/Api/DomainRecord.php#L29

After that, you can update any of the values associated with the record.

**Comment by iRuisu** [comment]
Much appreciated @Teevio, looking at the source code makes it easier to know what params to give!

**Comment by yassirh** [comment]
@Teevio Thank you for the response.

@iRuisu Your question made me realize that the library could use some documentation. It is now available here : https://cdn.rawgit.com/toin0u/DigitalOceanV2/master/documentation/index.html

For the domain records update : https://cdn.rawgit.com/toin0u/DigitalOceanV2/master/documentation/classes/DigitalOceanV2.Api.DomainRecord.html#method_update
