### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by enygma** [toin0u/DigitalOceanV2#191]
It looks like there's been some useful stuff added since the last release (`2.2.0` back in April 2017) . Any chance we could get a newer version to get some of these goodies?

**Comment by cballou** [comment]
I'm in the same boat as @enygma on this one. I had to go cowboy and require `"toin0u/digitalocean-v2": "dev-master"`. You then need to couple this with `"minimum-stability": "dev"` which is less than ideal.

**Comment by GrahamCampbell** [comment]
Released 2.3.0.

> Even crazier, I did this to override the dependency from "graham-campbell/digitalocean": "^5.0" which still points to ^2.0

That version constraint should give you the latest 2.x not just 2.0.x.
