### ISSUE TITLE
Appears to break with Buzz v0.16.1

### ISSUE THREAD

**Issue by ghost** [toin0u/DigitalOceanV2#195]
Appears to fail with the latest release of [Buzz](https://github.com/kriswallsmith/Buzz)

I haven't looked too closely, but it appears to not be sending the bearer token via the preSend listeners.

**Comment by lukepolo** [comment]
I also am getting this

**Comment by codegeek1001** [comment]
yea, i am also seeing an issue where I get "Call to undefined method Buzz\Browser::addListener()". Since buzz 0.17, they removed the Listeners but this library has not updated for that change.

**Comment by hailite** [comment]
Same issue here.
```
PHP Fatal error:  Uncaught Error: Call to undefined method Buzz\Browser::addListener() in vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php:40
Stack trace:
#0 test.php(9): DigitalOceanV2\Adapter\BuzzAdapter->__construct('xxxx...')
#1 {main}
  thrown in vendor/toin0u/digitalocean-v2/src/Adapter/BuzzAdapter.php on line 40
```

**Comment by TensorTom** [comment]
There is still no solution to this. It doesn't matter which adapter I use. I still get this error.

`PHP Fatal error:  Uncaught Error: Call to undefined method Buzz\Browser::addListener()`

**Comment by GrahamCampbell** [comment]
Does it work with Buzz 0.15.2?

**Comment by GrahamCampbell** [comment]
> Since buzz 0.17, they removed the Listeners but this library has not updated for that change.

We can't support the latest version of buzz without breaking support for existing versions. We should update our readme to give the supported ranges, and then make a second issue to the backlog for supporting either new buzz, or using phphttp or something.

**Comment by GrahamCampbell** [comment]
You will need this version of Buzz, rather than what was previously documented:

> "kriswallsmith/buzz": "^0.16",

This should work with PHP 5.4 - 7.3.

**Comment by GrahamCampbell** [comment]
2.3.0 released, with support for older buzz versions. master (3.x) will work with newer buzz versions.
