### ISSUE TITLE
Catch: Unable to authenticate you. 

### ISSUE THREAD

**Issue by newbreed65** [toin0u/DigitalOceanV2#203]
Im trying to catch errors when the API key for DO is wrong but cant seem get the catch statement correct. 

Can anyone advise? 

use DigitalOceanV2\Adapter\GuzzleHttpAdapter;
use DigitalOceanV2\DigitalOceanV2;
use DigitalOceanV2\Exception;
 
try { 
            $userInformation = $account->getUserInformation();
} catch (DigitalOceanV2\Exception\HttpException $e) {
            echo 'failed auth';
}

![screen shot 2018-09-25 at 17 24 33](https://user-images.githubusercontent.com/1533345/46028254-f4181f00-c0e7-11e8-96c9-266589dd58be.png)

**Comment by GhaziTriki** [comment]
Hello,

Why was this issue closed? I started using this library and I still have this issue. I get `Unable to authenticate you`
