### ISSUE TITLE
Build error on php hhvm and php 7.1

### ISSUE THREAD

**Issue by yassirh** [toin0u/DigitalOceanV2#206]
Specs fail when running on hhvm and php 7.1

![image](https://user-images.githubusercontent.com/4649139/47209097-d27d2100-d38f-11e8-9db5-8b0c8638bfed.png)

**Comment by yassirh** [comment]
@GrahamCampbell can you help me with this ?

**Comment by GrahamCampbell** [comment]
The error is because semantic versioning allows buzz to make breaking changes. All we need to do is correctly bound what version we require, and we're done.
