### ISSUE TITLE
2.3.0 Release Checklist

### ISSUE THREAD

**Issue by GrahamCampbell** [toin0u/DigitalOceanV2#223]
Ok, I think we should do a 2.3.0 release at the end of this month. What do we want to have included?

**Comment by jankremlacek** [comment]
CDN Endpoints support
https://developers.digitalocean.com/documentation/v2/#cdn-endpoints

**Comment by browner12** [comment]
TTL Support

https://github.com/toin0u/DigitalOceanV2/commit/b90847db5780e5060bd2188ad56a8c227b918b09

**Comment by GrahamCampbell** [comment]
I've spun off a 2.3.x branch, and master is now 3.x, with support for the latest version of Buzz.
