### ISSUE TITLE
Tagging Resources Throws a Runtime Exception

### ISSUE THREAD

**Issue by matt-croft** [toin0u/DigitalOceanV2#254]
When tagging resources it returns a 204 Status Code Response. 

https://developers.digitalocean.com/documentation/v2/#tag-a-resource

This is done via the post method in the abstract api, the ResponseMediator will check for the 204 and return null, 
but the AbstractApi will then throw a runtime exception because the content is null.

**Comment by GrahamCampbell** [comment]
Thanks for the report. What version of this package are you using, please?

**Comment by matt-croft** [comment]
Currently using the v3.0.0 tagged version
