### ISSUE TITLE
Feature Request: CDN Endpoints

### ISSUE THREAD

**Issue by timramseyjr** [toin0u/DigitalOceanV2#260]
Are there any plan to offer support for CDN Endpoints?

https://developers.digitalocean.com/documentation/v2/#cdn-endpoints

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I'd review any PR to add support. Alternatively, I would be willing to implement it for a fee. :)

**Comment by khrizt** [comment]
I've added a PR for [CDN Endpoints support](https://github.com/DigitalOceanPHP/Client/pull/284)
