### ISSUE TITLE
Feature request: API for Apps

### ISSUE THREAD

**Issue by shihjay2** [toin0u/DigitalOceanV2#262]
Any plans to include functions for the [Apps Platform](https://developers.digitalocean.com/documentation/v2/#apps)?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Please email me if you'd like a quote for this to be developed any added to this package.

**Comment by GrahamCampbell** [comment]
Will be available in the 4.1.0 release. In the meanwhile, you can use `^4.1@dev` to install it.
