### ISSUE TITLE
DomainRecord create method missing optional name attribute for NS records

### ISSUE THREAD

**Issue by LewisSmallwood** [toin0u/DigitalOceanV2#265]
Hi there,

The content for the `create()` method of `DomainRecord` is missing the "name" attribute for records of type "NS".

Although not explicitly stated in the documentation provided by DO for this method, the API does accept the name attribute as optional.

It would be great to modify the API to allow this as an optional record, defaulting back to @ if not provided.

**Comment by LewisSmallwood** [comment]
Upon further investigation, and contrary to the documentation from DO, the name attribute is required.

Without it this error is thrown:

![image](https://user-images.githubusercontent.com/1150414/105714517-5bdb1080-5f14-11eb-89b4-a0f925291277.png)

I have updated the PR accordingly.

**Comment by GrahamCampbell** [comment]
Thanks!
