### ISSUE TITLE
Create droplet private_networking property deprecated

### ISSUE THREAD

**Issue by LewisSmallwood** [toin0u/DigitalOceanV2#268]
In reference to [the docs](https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet), the `private_networking` attribute has been deprecated as of April 2020 and should be replaced with the new `vpc_uuid` attribute.

**Comment by GrahamCampbell** [comment]
I'd consider a PR to make it possible to use the new attribute, in a BC-preserving way.

**Comment by GrahamCampbell** [comment]
Will be fixed in the next 4.2.x release.
