### ISSUE TITLE
Floating IP assign/unassign methods should take in the IP address string rather than int.

### ISSUE THREAD

**Issue by LewisSmallwood** [toin0u/DigitalOceanV2#269]
The assign and unassign methods for Floating IPs should take in an IP Address identifier as a string rather than int values.

Will open PR for this shortly.

**Comment by GrahamCampbell** [comment]
Will be fixed in the next 4.1.x release.

**Comment by LewisSmallwood** [comment]
> Will be fixed in the next 4.1.x release.

How often do releases happen @GrahamCampbell?

**Comment by LewisSmallwood** [comment]
Hey @GrahamCampbell, any chance you could release 4.1.1 soon?

I'm waiting on the floating IP functionality to be added to Laravel 😄 

Cheers 🍻
