### ISSUE TITLE
Unknown named parameter $type when using pagination with array

### ISSUE THREAD

**Issue by kcalliauw** [toin0u/DigitalOceanV2#279]
Hello!

Below error when calling this:

    $imageTypeFilter = ['type' => 'distribution'];
    $images = $pager->fetchAll($client->image(), 'getAll', $imageTypeFilter);

![image](https://user-images.githubusercontent.com/1638303/110471828-e8185000-80dc-11eb-90ce-c1ec8fd4c847.png)

Not exactly sure why this happens, but changing `...$parameters` to just `$parameters` on ResultPager.php line 87 fixes the issue in this specific case. Not sure if this breaks other things.

**Comment by GrahamCampbell** [comment]
This is because your array needs to be of the format `['distribution']` and not `['type' => 'distribution']`. PHP 8 has started to be fussy about this.

**Comment by kcalliauw** [comment]
This yields another error.
Also I don't understand how this would be the solution. The getAll function for the Image API can take both "type" as a parameter and "private". Passing that array `['distribution']` just yields a string inside that function, while it's expecting an associative array, as far as I can see in the code.

![image](https://user-images.githubusercontent.com/1638303/110478050-2feea580-80e4-11eb-9884-c0aa54bae524.png)

**Comment by GrahamCampbell** [comment]
Oh, you need `[['type' => 'distribution']]`, then.

**Comment by kcalliauw** [comment]
Worked like a charm! Thank you :+1:
