### ISSUE TITLE
Release 4.2.1 to include fix for missing `$vpcUuid` default value 

### ISSUE THREAD

**Issue by webignition** [toin0u/DigitalOceanV2#280]
#277 adds a missing default value for `$vpcUuid` when calling `Droplet::create()`.

This fix has was merged into master after 4.2.0 was released. 

Can we have a minor 4.2.1 release which is basically `4.2` up to `6893187fefa8c81ef095ac8dcd918497a37d8860`?

**Comment by GrahamCampbell** [comment]
Yes and no. There will be a release soon, but no, it's not happening today. You can still install this code using `^4.2.1` even if there is no tag, by using dev stability in combination with prefer-stable in your app's composer.json file.

**Comment by webignition** [comment]
Cool, cheers :+1:
