### ISSUE TITLE
Policy on PHP 8 named argument usage?

### ISSUE THREAD

**Issue by webignition** [toin0u/DigitalOceanV2#287]
Have there been any thoughts or decisions made on whether to support the use of [PHP 8's named argument feature][1] in calling code?

Clearly you cannot stop calling code from choosing to use a named argument approach but you can choose whether to opt to avoid BC breaks by never changing argument names.

Some projects have chosen to explicitly support named arguments (making argument names part of the public API and unchangeable without a BC break) and some projects (Symfony being the largest I can think of) that explicitly state that argument names are not fixed and are subject to change.

Any thoughts on this? Asking as I am considering using named arguments in some code.

[1]: https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. The policy for now is that argument names are not included in the BC promise, just like Laravel.
