### ISSUE TITLE
Api\Image::getById() accepts only int, should accept int|string

### ISSUE THREAD

**Issue by webignition** [toin0u/DigitalOceanV2#297]
`Api\Image::getById()` is [type-hinted to accept an `int` argument](https://github.com/DigitalOceanPHP/Client/blob/7daf50d13372795f5ddeeb4510836662a9c71ce2/src/Api/Image.php#L60):

```php
public function getById(int $id) {
    // ...
}
```

The [DigitalOcean API docs for this feature](https://docs.digitalocean.com/reference/api/api-reference/#operation/get_image) state that the `image_id` parameter can be either `int` or `string`.

This isn't a significant problem for me as any images that I need to get are ones that I have created myself and which all have numeric-only identifiers. This is, however, a minor problem as I have to cast values to int before calling `Api\Image::getById()` to stop phpstan from being sad.

I'm not sure what the best fix would be here. 

Ideally a union type could be used (`public function getById(int|string $id)`), however that is only possible with PHP 8.0+ and this library supports `^7.2.5 || ^8.0`

One option would be to remove the type hint entirely and within the method check if the argument is either `is_int()` or `is_string()` and throw an exception if not?

```php
/**
 * @param int|string $id
 *
 * @throws ExceptionInterface
 *
 * @return ImageEntity
 */
public function getById($id)
{
    if (!\is_int($id) && !\is_string($id)) {
        throw new InvalidArgumentException('$id must be an int or a string');
    }

    $image = $this->get(\sprintf('images/%d', $id));

    return new ImageEntity($image->image);
}
```

Another option (which is still perfectly valid) is to do nothing for now, wait until supporting only PHP 8.0+ and use a union type.

**Comment by GrahamCampbell** [comment]
Thanks, but the integer ids are fine. Their docs say both private and public images have integer ids. The slugs are just an alternative way to reference some public images. We're not gonna support that here. :)

**Comment by webignition** [comment]
Fair enough :)
