### ISSUE TITLE
Ubuntu 20.04 composer install fail

### ISSUE THREAD

**Issue by sirchuck** [toin0u/DigitalOceanV2#298]
Is there a new name for the package requirement I should use, v2:^4.4 isn't working on Ubuntu 20.04?

composer require "toin0u/digitalocean-v2:^4.4"
_______RESPONSE_______________________
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires toin0u/digitalocean-v2 ^4.4, found toin0u/digitalocean-v2[4.4.x-dev] but it does not match your minimum-stability.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
_________________________________________
Also, if it helps anyone who tries to copy-paste the code after 20 hours of programming, make sure you take out the dollar sign before the composer require statements. :D

**Comment by GrahamCampbell** [comment]
There is no v4.4.0 tag yet, sorry. Please use the instructions from the 4.3 branch for now.
