### ISSUE TITLE
Meta.php Entity class, what is it for?

### ISSUE THREAD

**Issue by sdwru** [toin0u/DigitalOceanV2#301]
I don't see Meta class used anywhere in the code or mentioned in the docs.  I can see what it is intended to access on the API but how do I use it?  Seems to me there should maybe be a generic method in AbstractApi.php to access it.  Perhaps just using something like 
```
__call($method, $args) {
  // Some code to access MetaEntity
}
```

**Comment by GrahamCampbell** [comment]
Correct, there is no meta entity, and it is not intended that consumers of this library should need to access it. This library already provides a pagination abstraction.
