### ISSUE TITLE
PHP 7.4 requirement

### ISSUE THREAD

**Issue by sdwru** [toin0u/DigitalOceanV2#302]
Any chance you can lower that to php 7.3?  We still use that for several things and it would be difficult to upgrade.

**Comment by GrahamCampbell** [comment]
No plans. If you are happy with an EOL version of PHP, you can also be happy with an older version of this library, from before we dropped support. :)

**Comment by GrahamCampbell** [comment]
v4.4.0 was the last release to support PHP 7.3.

**Comment by sdwru** [comment]
If the reason is because 7.3 is EOL there is no reason to enforce that in a peripheral library imo.  This library has not been keeping up with changes to the API, seems to me that should be a higher priority. We are probably going to have to fork this now because we need the changes that we ourselves have submitted pull requests on.  There won't be much incentive to do that once we are using our own fork.

**Comment by sdwru** [comment]
Using old versions is not an option because we contributed some new things that the project has not kept up with.  Seems to me those priorities are backwards but that's just me.  By raising the PHP version you are guaranteeing that we will need to fork and maintain our own version, therefore stifling contributions.

**Comment by GrahamCampbell** [comment]
I'd highly recommend putting in the effort to upgrade to PHP 7.4.

**Comment by sdwru** [comment]
> I'd highly recommend putting in the effort to upgrade to PHP 7.4.

WHMCS has only started supporting PHP 7.4 with their latest release and I don't see them supporting PHP 8 anytime soon.  I have no control over that.

As I said before, if your reason for doing it is because 7.3 is EOL that shouldn't be enforced in a peripheral library anyways imo.  Anyone who wants/needs to use a newer version still can.
