### ISSUE TITLE
Add support for Project Resources API

### ISSUE THREAD

**Issue by spicybeefnoodle** [toin0u/DigitalOceanV2#303]
https://docs.digitalocean.com/reference/api/api-reference/#tag/Project-Resources

When you create a new resource (for instance, a droplet), there is no option to assign it to a specific project at the same time. It simply attaches itself to the default project, which is not handy when you have multiple projects going. You have to do it afterwards using the Project Resources API.

> "The DigitalOcean API does not currently support assigning resources to a specific project when the resource is created. Currently, this require a second API call."
> source: https://github.com/digitalocean/doctl/issues/630#issuecomment-620227791

I didn't see that implemented in the SDK so it might be a handy one to have.

**Comment by mohameedsherif** [comment]
why not exists in last version?
