### ISSUE TITLE
"Floating IPs" have been renamed to "Reserved IPs"

### ISSUE THREAD

**Issue by LucaRed** [toin0u/DigitalOceanV2#307]
The "Floating IP" endpoints have been renamed to "Reserved IP".

[From the official release notes](https://docs.digitalocean.com/release-notes/#2022-06-16):

> We have renamed the Floating IP product to [Reserved IPs](https://docs.digitalocean.com/products/networking/reserved-ips/). The Reserved IP service retains the same functionality as the prior service.
>
> We have added new [API endpoints](https://docs.digitalocean.com/reference/api/api-reference/#tag/Reserved-IPs) and fields (reserved_ips) to reflect the name change, but the service’s original [Floating IP endpoints](https://docs.digitalocean.com/reference/api/api-reference/#tag/Floating-IPs) and fields (floating_ips) will remain available until the fall of 2023. Please update any automation, scripts, or services that use these endpoints to reflect these changes.

**Comment by LucaRed** [comment]
This issue is not stale.

**Comment by GrahamCampbell** [comment]
Thanks for letting us know. I'd review a PR to implement this, but I don't have capacity to implement this at this time. Consider [sponsoring me](https://github.com/sponsors/GrahamCampbell), which would allow me to allocate more time to OSS. I am spread across many OSS repos, including Guzzle.
