### ISSUE TITLE
Droplet entity missing VPC UUID property

### ISSUE THREAD

**Issue by phillip-elm** [toin0u/DigitalOceanV2#311]
I'm new to this library so I could be mistaken, but it appears that the Droplet entity is missing the `vpc_uuid` property present in the [DO API](https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_get).

**Comment by GrahamCampbell** [comment]
I'd review a PR to implement this, but I don't have capacity to implement this at this time. Consider [sponsoring me](https://github.com/sponsors/GrahamCampbell), which would allow me to allocate more time to OSS. I am spread across many OSS repos, including Guzzle.
