### ISSUE TITLE
Kubernetes support? 

### ISSUE THREAD

**Issue by ingageco** [toin0u/DigitalOceanV2#312]
I'm looking through the entities and it doesn't look like there are any related to DO Managed Kubernetes. Does this package support DO kubernetes? 

I'm looking to scale nodes via the api.

**Comment by GrahamCampbell** [comment]
I'd review a PR to implement this, but I don't have capacity to implement this at this time. Consider [sponsoring me](https://github.com/sponsors/GrahamCampbell), which would allow me to allocate more time to OSS. I am spread across many OSS repos, including Guzzle.
