### ISSUE TITLE
Uptime Checks

### ISSUE THREAD

**Issue by ryangurn** [toin0u/DigitalOceanV2#313]
I have noticed that this php library does not include methods for checking uptime information as documented in the official digital ocean api specification.

Is it possible to get that added?

https://docs.digitalocean.com/reference/api/api-reference/#operation/uptime_checks_list

**Comment by GrahamCampbell** [comment]
I'd review a PR to implement this, but I don't have capacity to implement this at this time. Consider [sponsoring me](https://github.com/sponsors/GrahamCampbell), which would allow me to allocate more time to OSS. I am spread across many OSS repos, including Guzzle.
