### ISSUE TITLE
Please remove "final" keyword from ExceptionThrower to allow extending this class.

### ISSUE THREAD

**Issue by lhridley** [toin0u/DigitalOceanV2#326]
Currently the `HttpClient\Plugin\ExceptionThrower` class has the PHP final keyword applied at the class level, which prevents extending the class and overriding the the public handler to more gracefully handle exceptions for applications utilizing the library.

Please consider removing the "final" keyword from this class.

**Comment by GrahamCampbell** [comment]
Why is it not possible to use composition to achieve what you need, rather than extension?

**Comment by GrahamCampbell** [comment]
Actually, you should make your own class from scratch. Our class is marked as internal, which means it is not included in our BC promise and may even be deleted in a patch release.
