### ISSUE TITLE
Escape double quotes when create TXT domain record with double quotes

### ISSUE THREAD

**Issue by fabiopaiva** [toin0u/DigitalOceanV2#73]
The problem is in file DigitalOceanV2\Api\DomainRecord line 71
If i have a TXT record with double quotes, eg
"v=spf1 mx include:mailserver ?all"
the result is
{"name":"mydomain", "type":"TXT", "data":""v=spf1 mx include:mailserver ?all""}
Causing error 500

**Comment by toin0u** [comment]
Thank you for reporting this :) Do you mind to make a PR ?

**Comment by fabiopaiva** [comment]
Done

**Comment by toin0u** [comment]
Thank you :)

**Comment by fabiopaiva** [comment]
happy to contribute
