### ISSUE TITLE
Getting droplet IP the right way?

### ISSUE THREAD

**Issue by Forge-Media** [toin0u/DigitalOceanV2#76]
Hi

I'm having a little bit of an issue, depending on how a Droplet is made (Private networking on or off) the returned Network Array will be slightly different.

I currently get the Droplet's Public IP as such:
```
$ip = $userAtom->networks[0]->ipAddress (For a Droplet with Private networking turned off)
&
$ip = $userAtom->networks[1]->ipAddress (For a Droplet with Private networking turned on) 
```
This is causing me a headache, is there no way to get the Droplet's Public IP regardless of the Private networking status, with a single statement?

Just seems a little annoying that *$userAtom->ipAddress* does not work.

**For instance:**
using  $userAtom->networks[1]. (with Private network off results in no IP being found).

**Comment by toin0u** [comment]
Thanks for reporting this @Forge-Media. We will look at it :)

**Comment by toin0u** [comment]
Hi @Forge-Media 

I've given a closer look at this. I don't think it's an issue because you can solve the problem which is, how to get the public IP of a given droplet.

This can be solved with something like:
```php
$ips = array_map(function ($network) {
    if ('public' === $network->type) {
        return $network->ipAddress;
    }
}, $userAtom->networks);

echo $ips[0];
```

Of course, we could provide a helper function but I don't think it's the scope of the lib.

Anyway, hope that helps.

**Comment by lfxc** [comment]
explaining how to use the array_map function to get the pulbic ip's was very helpful.   Please consider adding it to the "howto" page for others.
