### ISSUE TITLE
So Broken.

### ISSUE THREAD

**Issue by taylorotwell** [toin0u/DigitalOceanV2#77]
Why does this library **still** break every time DigitalOcean adds a new property to their API? Is this library supposed to be used in production applications?

Property "DigitalOceanV2\Entity\Droplet::nextBackupWindow" should exist.

**Comment by toin0u** [comment]
@taylorotwell Sorry for that.. DigitalOcean changes their API by adding / deleting some properties without warning. If you look at the documentation, the property `nextBackupWindow` is not documented at all.. But you're right, we need to find a better way to avoid those exceptions.
