### ISSUE TITLE
droplet->getById

### ISSUE THREAD

**Issue by cphubs** [toin0u/DigitalOceanV2#78]
Hi

$droplet123 = $droplet->getById(4124085);

{"status":false,"message":"Property \"DigitalOceanV2\\Entity\\Droplet::nextBackupWindow\" should exist.","data":""}

I use 
"toin0u/digitalocean-v2": "0.5.*@dev" 
"kriswallsmith/buzz": "0.13.*",

**Comment by toin0u** [comment]
Thank @cphubs for the report. This should be fixed now https://github.com/toin0u/DigitalOceanV2/releases/tag/0.4.2
