### ISSUE TITLE
Can't request droplets

### ISSUE THREAD

**Issue by kwartel** [toin0u/DigitalOceanV2#82]
When I request a droplet (getAll or getByID), I get the the following error:
![knipsel](https://cloud.githubusercontent.com/assets/3989063/6285346/01102b10-b8fb-11e4-9f47-a9dd3bee84dd.PNG)
This is my code:
```
<?php

require 'vendor/autoload.php';

use DigitalOceanV2\Adapter\BuzzAdapter;
use DigitalOceanV2\DigitalOceanV2;

$adapter = new BuzzAdapter($token);

$digitalocean = new DigitalOceanV2($adapter);

$droplet = $digitalocean->droplet();

$droplet = $droplet->getAll();
```
Other requests work.

**Comment by taylorotwell** [comment]
Same. Library totally broken.

**Comment by Forge-Media** [comment]
try this:
```require 'vendor/autoload.php';

use DigitalOceanV2\Adapter\GuzzleAdapter;
use DigitalOceanV2\DigitalOceanV2;

// create an adapter with your access token which can be
// generated at https://cloud.digitalocean.com/settings/applications
$adapter = new GuzzleAdapter('');

// create a digital ocean object with the previous adapter
$digitalocean = new DigitalOceanV2($adapter);

//return the droplet api
$droplet = $digitalocean->droplet();```

At the moment mine is working, I never managed to get the BuzzAdapter to work.

**Comment by toin0u** [comment]
@kwartel@taylorotwell which version do you use ? `0.5` should fix it.. https://github.com/toin0u/DigitalOceanV2#entities
@Forge-Media thanks for your snippet.

**Comment by ameliaikeda** [comment]
@toin0u PR is on its way, just spent a little bit figuring out how this actually happens.

**Comment by toin0u** [comment]
@ameliaikeda Thanks but when I'm using the `0.5` version, I cannot reproduce it.. Anyway, I'll looking forward to your PR :)

**Comment by taylorotwell** [comment]
I'm using the 0.5 version and creating Droplets with Buzz adapter is
broken. I switched to just not even using the SDK and just using plain
Guzzle.

**Comment by toin0u** [comment]
@taylorotwell thanks for your feedbacks. I'll look at the Buzz adapter asap.

**Comment by taylorotwell** [comment]
Nice. The `create` method on the SDK is the only method I ever have issues with so I just use Guzzle for that and the SDK for everything else :smile:

**Comment by toin0u** [comment]
@taylorotwell Thanks for this precision - I update the issue and look at this closer asap.

**Comment by kwartel** [comment]
I replaced the buzz adapter and it works. :) I tried Guzzle5 before and that didn't work out so well, but this is great! :+1:
