### ISSUE TITLE
Library is broken again.

### ISSUE THREAD

**Issue by taylorotwell** [toin0u/DigitalOceanV2#83]
Missing another property. Seriously.

Property "DigitalOceanV2\Entity\Droplet::size" should exist.

**Comment by GrahamCampbell** [comment]
Really?

**Comment by GrahamCampbell** [comment]
Are you using 0.5.x?

**Comment by GrahamCampbell** [comment]
That was meant to fix this.

**Comment by taylorotwell** [comment]
Ah I'll get upgraded!

**Comment by toin0u** [comment]
I though the API changed again x_X
Happy to hear it's working.. :+1:
