### ISSUE TITLE
Issue when creating droplet with Buzz adapter

### ISSUE THREAD

**Issue by toin0u** [toin0u/DigitalOceanV2#86]
See: https://github.com/toin0u/DigitalOceanV2/issues/82#issuecomment-75468565

The issue is with the `create` method: https://github.com/toin0u/DigitalOceanV2/issues/82#issuecomment-75470173

**Comment by GrahamCampbell** [comment]
This could be solved by #75 could it not?

**Comment by GrahamCampbell** [comment]
Just tested creating a droplet using buzz 0.15, guzzle 3.9, guzzle 5.3, and guzzle 6.1. All of them worked.
