### ISSUE TITLE
Feature request: all user images

### ISSUE THREAD

**Issue by kwartel** [toin0u/DigitalOceanV2#87]
In the api, there is an option to call: /v2/images?type=application
This only requests the user images. This takes a lot less time then requesting all the images and filtering them.

**Comment by toin0u** [comment]
That's a good idea :) Let's do it!

**Comment by toin0u** [comment]
@kwartel Here you go :) https://github.com/toin0u/DigitalOceanV2/releases/tag/0.5.2
