### ISSUE TITLE
"API v2 Officially Leaves Beta"

### ISSUE THREAD

**Issue by GrahamCampbell** [toin0u/DigitalOceanV2#95]
https://www.digitalocean.com/company/blog/apiv2-officially-leaves-beta/

Are we nearing a point to tag a stable release here?

**Comment by yassirh** [comment]
(y)

**Comment by yassirh** [comment]
:+1:

**Comment by toin0u** [comment]
@GrahamCampbell @yassirh done! https://github.com/toin0u/DigitalOceanV2/releases/tag/1.0.0
