### ISSUE TITLE
QQ: Why should we specify dependencies manually?

### ISSUE THREAD

**Issue by meglio** [toin0u/DigitalOceanV2#98]
Hello,

In your installation instructions, you say we should include guzzle and buzz manually in our composer.json - why can't it just be an auto-installed dependency?

**Comment by GrahamCampbell** [comment]
Because users should have a choice which one they use. Installing them both would be silly, and could cause conflicts.

**Comment by GrahamCampbell** [comment]
You should include ONE of them, not both, unless you plan to use both adapters for some reason?

**Comment by meglio** [comment]
Okay I see - only one of them. Now it makes sense. Thank you for clarifying.
